/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OwnerFacilityRouteImport } from './routes/owner-facility'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FarmerStorageRouteImport } from './routes/farmer-storage'
import { Route as FarmerDetailsRouteImport } from './routes/farmer-details'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as FarmerIndexRouteImport } from './routes/farmer.index'
import { Route as OwnerStorageSuccessRouteImport } from './routes/owner.storage-success'
import { Route as OwnerMarketInsightsRouteImport } from './routes/owner.market-insights'
import { Route as OwnerContactRouteImport } from './routes/owner.contact'
import { Route as OwnerBookingsRouteImport } from './routes/owner.bookings'
import { Route as OwnerAddRouteImport } from './routes/owner.add'
import { Route as FarmerPaymentRouteImport } from './routes/farmer.payment'
import { Route as FarmerInsightsRouteImport } from './routes/farmer.insights'
import { Route as FarmerContractRouteImport } from './routes/farmer.contract'
import { Route as FarmerContactRouteImport } from './routes/farmer.contact'
import { Route as FarmerAlertsRouteImport } from './routes/farmer.alerts'
import { Route as FarmerActiveRouteImport } from './routes/farmer.active'
import { Route as FarmerStorageIndexRouteImport } from './routes/farmer.storage.index'
import { Route as FarmerStorageIdRouteImport } from './routes/farmer.storage.$id'

const OwnerFacilityRoute = OwnerFacilityRouteImport.update({
  id: '/owner-facility',
  path: '/owner-facility',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerStorageRoute = FarmerStorageRouteImport.update({
  id: '/farmer-storage',
  path: '/farmer-storage',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerDetailsRoute = FarmerDetailsRouteImport.update({
  id: '/farmer-details',
  path: '/farmer-details',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerIndexRoute = FarmerIndexRouteImport.update({
  id: '/farmer/',
  path: '/farmer/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerStorageSuccessRoute = OwnerStorageSuccessRouteImport.update({
  id: '/owner/storage-success',
  path: '/owner/storage-success',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerMarketInsightsRoute = OwnerMarketInsightsRouteImport.update({
  id: '/owner/market-insights',
  path: '/owner/market-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerContactRoute = OwnerContactRouteImport.update({
  id: '/owner/contact',
  path: '/owner/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerBookingsRoute = OwnerBookingsRouteImport.update({
  id: '/owner/bookings',
  path: '/owner/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerAddRoute = OwnerAddRouteImport.update({
  id: '/owner/add',
  path: '/owner/add',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerPaymentRoute = FarmerPaymentRouteImport.update({
  id: '/farmer/payment',
  path: '/farmer/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerInsightsRoute = FarmerInsightsRouteImport.update({
  id: '/farmer/insights',
  path: '/farmer/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerContractRoute = FarmerContractRouteImport.update({
  id: '/farmer/contract',
  path: '/farmer/contract',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerContactRoute = FarmerContactRouteImport.update({
  id: '/farmer/contact',
  path: '/farmer/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerAlertsRoute = FarmerAlertsRouteImport.update({
  id: '/farmer/alerts',
  path: '/farmer/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerActiveRoute = FarmerActiveRouteImport.update({
  id: '/farmer/active',
  path: '/farmer/active',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerStorageIndexRoute = FarmerStorageIndexRouteImport.update({
  id: '/farmer/storage/',
  path: '/farmer/storage/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerStorageIdRoute = FarmerStorageIdRouteImport.update({
  id: '/farmer/storage/$id',
  path: '/farmer/storage/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/farmer-details': typeof FarmerDetailsRoute
  '/farmer-storage': typeof FarmerStorageRoute
  '/help': typeof HelpRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/orders': typeof OrdersRoute
  '/owner-facility': typeof OwnerFacilityRoute
  '/farmer/active': typeof FarmerActiveRoute
  '/farmer/alerts': typeof FarmerAlertsRoute
  '/farmer/contact': typeof FarmerContactRoute
  '/farmer/contract': typeof FarmerContractRoute
  '/farmer/insights': typeof FarmerInsightsRoute
  '/farmer/payment': typeof FarmerPaymentRoute
  '/owner/add': typeof OwnerAddRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/contact': typeof OwnerContactRoute
  '/owner/market-insights': typeof OwnerMarketInsightsRoute
  '/owner/storage-success': typeof OwnerStorageSuccessRoute
  '/farmer/': typeof FarmerIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/farmer/storage/$id': typeof FarmerStorageIdRoute
  '/farmer/storage/': typeof FarmerStorageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/farmer-details': typeof FarmerDetailsRoute
  '/farmer-storage': typeof FarmerStorageRoute
  '/help': typeof HelpRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/orders': typeof OrdersRoute
  '/owner-facility': typeof OwnerFacilityRoute
  '/farmer/active': typeof FarmerActiveRoute
  '/farmer/alerts': typeof FarmerAlertsRoute
  '/farmer/contact': typeof FarmerContactRoute
  '/farmer/contract': typeof FarmerContractRoute
  '/farmer/insights': typeof FarmerInsightsRoute
  '/farmer/payment': typeof FarmerPaymentRoute
  '/owner/add': typeof OwnerAddRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/contact': typeof OwnerContactRoute
  '/owner/market-insights': typeof OwnerMarketInsightsRoute
  '/owner/storage-success': typeof OwnerStorageSuccessRoute
  '/farmer': typeof FarmerIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/farmer/storage/$id': typeof FarmerStorageIdRoute
  '/farmer/storage': typeof FarmerStorageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/farmer-details': typeof FarmerDetailsRoute
  '/farmer-storage': typeof FarmerStorageRoute
  '/help': typeof HelpRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/orders': typeof OrdersRoute
  '/owner-facility': typeof OwnerFacilityRoute
  '/farmer/active': typeof FarmerActiveRoute
  '/farmer/alerts': typeof FarmerAlertsRoute
  '/farmer/contact': typeof FarmerContactRoute
  '/farmer/contract': typeof FarmerContractRoute
  '/farmer/insights': typeof FarmerInsightsRoute
  '/farmer/payment': typeof FarmerPaymentRoute
  '/owner/add': typeof OwnerAddRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/contact': typeof OwnerContactRoute
  '/owner/market-insights': typeof OwnerMarketInsightsRoute
  '/owner/storage-success': typeof OwnerStorageSuccessRoute
  '/farmer/': typeof FarmerIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/farmer/storage/$id': typeof FarmerStorageIdRoute
  '/farmer/storage/': typeof FarmerStorageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/farmer-details'
    | '/farmer-storage'
    | '/help'
    | '/kyc'
    | '/login'
    | '/market'
    | '/orders'
    | '/owner-facility'
    | '/farmer/active'
    | '/farmer/alerts'
    | '/farmer/contact'
    | '/farmer/contract'
    | '/farmer/insights'
    | '/farmer/payment'
    | '/owner/add'
    | '/owner/bookings'
    | '/owner/contact'
    | '/owner/market-insights'
    | '/owner/storage-success'
    | '/farmer/'
    | '/owner/'
    | '/farmer/storage/$id'
    | '/farmer/storage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/farmer-details'
    | '/farmer-storage'
    | '/help'
    | '/kyc'
    | '/login'
    | '/market'
    | '/orders'
    | '/owner-facility'
    | '/farmer/active'
    | '/farmer/alerts'
    | '/farmer/contact'
    | '/farmer/contract'
    | '/farmer/insights'
    | '/farmer/payment'
    | '/owner/add'
    | '/owner/bookings'
    | '/owner/contact'
    | '/owner/market-insights'
    | '/owner/storage-success'
    | '/farmer'
    | '/owner'
    | '/farmer/storage/$id'
    | '/farmer/storage'
  id:
    | '__root__'
    | '/'
    | '/farmer-details'
    | '/farmer-storage'
    | '/help'
    | '/kyc'
    | '/login'
    | '/market'
    | '/orders'
    | '/owner-facility'
    | '/farmer/active'
    | '/farmer/alerts'
    | '/farmer/contact'
    | '/farmer/contract'
    | '/farmer/insights'
    | '/farmer/payment'
    | '/owner/add'
    | '/owner/bookings'
    | '/owner/contact'
    | '/owner/market-insights'
    | '/owner/storage-success'
    | '/farmer/'
    | '/owner/'
    | '/farmer/storage/$id'
    | '/farmer/storage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FarmerDetailsRoute: typeof FarmerDetailsRoute
  FarmerStorageRoute: typeof FarmerStorageRoute
  HelpRoute: typeof HelpRoute
  KycRoute: typeof KycRoute
  LoginRoute: typeof LoginRoute
  MarketRoute: typeof MarketRoute
  OrdersRoute: typeof OrdersRoute
  OwnerFacilityRoute: typeof OwnerFacilityRoute
  FarmerActiveRoute: typeof FarmerActiveRoute
  FarmerAlertsRoute: typeof FarmerAlertsRoute
  FarmerContactRoute: typeof FarmerContactRoute
  FarmerContractRoute: typeof FarmerContractRoute
  FarmerInsightsRoute: typeof FarmerInsightsRoute
  FarmerPaymentRoute: typeof FarmerPaymentRoute
  OwnerAddRoute: typeof OwnerAddRoute
  OwnerBookingsRoute: typeof OwnerBookingsRoute
  OwnerContactRoute: typeof OwnerContactRoute
  OwnerMarketInsightsRoute: typeof OwnerMarketInsightsRoute
  OwnerStorageSuccessRoute: typeof OwnerStorageSuccessRoute
  FarmerIndexRoute: typeof FarmerIndexRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  FarmerStorageIdRoute: typeof FarmerStorageIdRoute
  FarmerStorageIndexRoute: typeof FarmerStorageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/owner-facility': {
      id: '/owner-facility'
      path: '/owner-facility'
      fullPath: '/owner-facility'
      preLoaderRoute: typeof OwnerFacilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer-storage': {
      id: '/farmer-storage'
      path: '/farmer-storage'
      fullPath: '/farmer-storage'
      preLoaderRoute: typeof FarmerStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer-details': {
      id: '/farmer-details'
      path: '/farmer-details'
      fullPath: '/farmer-details'
      preLoaderRoute: typeof FarmerDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/': {
      id: '/farmer/'
      path: '/farmer'
      fullPath: '/farmer/'
      preLoaderRoute: typeof FarmerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/storage-success': {
      id: '/owner/storage-success'
      path: '/owner/storage-success'
      fullPath: '/owner/storage-success'
      preLoaderRoute: typeof OwnerStorageSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/market-insights': {
      id: '/owner/market-insights'
      path: '/owner/market-insights'
      fullPath: '/owner/market-insights'
      preLoaderRoute: typeof OwnerMarketInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/contact': {
      id: '/owner/contact'
      path: '/owner/contact'
      fullPath: '/owner/contact'
      preLoaderRoute: typeof OwnerContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/bookings': {
      id: '/owner/bookings'
      path: '/owner/bookings'
      fullPath: '/owner/bookings'
      preLoaderRoute: typeof OwnerBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/add': {
      id: '/owner/add'
      path: '/owner/add'
      fullPath: '/owner/add'
      preLoaderRoute: typeof OwnerAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/payment': {
      id: '/farmer/payment'
      path: '/farmer/payment'
      fullPath: '/farmer/payment'
      preLoaderRoute: typeof FarmerPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/insights': {
      id: '/farmer/insights'
      path: '/farmer/insights'
      fullPath: '/farmer/insights'
      preLoaderRoute: typeof FarmerInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/contract': {
      id: '/farmer/contract'
      path: '/farmer/contract'
      fullPath: '/farmer/contract'
      preLoaderRoute: typeof FarmerContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/contact': {
      id: '/farmer/contact'
      path: '/farmer/contact'
      fullPath: '/farmer/contact'
      preLoaderRoute: typeof FarmerContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/alerts': {
      id: '/farmer/alerts'
      path: '/farmer/alerts'
      fullPath: '/farmer/alerts'
      preLoaderRoute: typeof FarmerAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/active': {
      id: '/farmer/active'
      path: '/farmer/active'
      fullPath: '/farmer/active'
      preLoaderRoute: typeof FarmerActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/storage/': {
      id: '/farmer/storage/'
      path: '/farmer/storage'
      fullPath: '/farmer/storage/'
      preLoaderRoute: typeof FarmerStorageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/storage/$id': {
      id: '/farmer/storage/$id'
      path: '/farmer/storage/$id'
      fullPath: '/farmer/storage/$id'
      preLoaderRoute: typeof FarmerStorageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FarmerDetailsRoute: FarmerDetailsRoute,
  FarmerStorageRoute: FarmerStorageRoute,
  HelpRoute: HelpRoute,
  KycRoute: KycRoute,
  LoginRoute: LoginRoute,
  MarketRoute: MarketRoute,
  OrdersRoute: OrdersRoute,
  OwnerFacilityRoute: OwnerFacilityRoute,
  FarmerActiveRoute: FarmerActiveRoute,
  FarmerAlertsRoute: FarmerAlertsRoute,
  FarmerContactRoute: FarmerContactRoute,
  FarmerContractRoute: FarmerContractRoute,
  FarmerInsightsRoute: FarmerInsightsRoute,
  FarmerPaymentRoute: FarmerPaymentRoute,
  OwnerAddRoute: OwnerAddRoute,
  OwnerBookingsRoute: OwnerBookingsRoute,
  OwnerContactRoute: OwnerContactRoute,
  OwnerMarketInsightsRoute: OwnerMarketInsightsRoute,
  OwnerStorageSuccessRoute: OwnerStorageSuccessRoute,
  FarmerIndexRoute: FarmerIndexRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  FarmerStorageIdRoute: FarmerStorageIdRoute,
  FarmerStorageIndexRoute: FarmerStorageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
