/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as FarmerIndexRouteImport } from './routes/farmer.index'
import { Route as OwnerBookingsRouteImport } from './routes/owner.bookings'
import { Route as OwnerAddRouteImport } from './routes/owner.add'
import { Route as FarmerPaymentRouteImport } from './routes/farmer.payment'
import { Route as FarmerContractRouteImport } from './routes/farmer.contract'
import { Route as FarmerActiveRouteImport } from './routes/farmer.active'
import { Route as FarmerStorageIndexRouteImport } from './routes/farmer.storage.index'
import { Route as FarmerStorageIdRouteImport } from './routes/farmer.storage.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerIndexRoute = FarmerIndexRouteImport.update({
  id: '/farmer/',
  path: '/farmer/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerBookingsRoute = OwnerBookingsRouteImport.update({
  id: '/owner/bookings',
  path: '/owner/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerAddRoute = OwnerAddRouteImport.update({
  id: '/owner/add',
  path: '/owner/add',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerPaymentRoute = FarmerPaymentRouteImport.update({
  id: '/farmer/payment',
  path: '/farmer/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerContractRoute = FarmerContractRouteImport.update({
  id: '/farmer/contract',
  path: '/farmer/contract',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerActiveRoute = FarmerActiveRouteImport.update({
  id: '/farmer/active',
  path: '/farmer/active',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerStorageIndexRoute = FarmerStorageIndexRouteImport.update({
  id: '/farmer/storage/',
  path: '/farmer/storage/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerStorageIdRoute = FarmerStorageIdRouteImport.update({
  id: '/farmer/storage/$id',
  path: '/farmer/storage/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/farmer/active': typeof FarmerActiveRoute
  '/farmer/contract': typeof FarmerContractRoute
  '/farmer/payment': typeof FarmerPaymentRoute
  '/owner/add': typeof OwnerAddRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/farmer/': typeof FarmerIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/farmer/storage/$id': typeof FarmerStorageIdRoute
  '/farmer/storage/': typeof FarmerStorageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/farmer/active': typeof FarmerActiveRoute
  '/farmer/contract': typeof FarmerContractRoute
  '/farmer/payment': typeof FarmerPaymentRoute
  '/owner/add': typeof OwnerAddRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/farmer': typeof FarmerIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/farmer/storage/$id': typeof FarmerStorageIdRoute
  '/farmer/storage': typeof FarmerStorageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/farmer/active': typeof FarmerActiveRoute
  '/farmer/contract': typeof FarmerContractRoute
  '/farmer/payment': typeof FarmerPaymentRoute
  '/owner/add': typeof OwnerAddRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/farmer/': typeof FarmerIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/farmer/storage/$id': typeof FarmerStorageIdRoute
  '/farmer/storage/': typeof FarmerStorageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/help'
    | '/login'
    | '/market'
    | '/orders'
    | '/settings'
    | '/farmer/active'
    | '/farmer/contract'
    | '/farmer/payment'
    | '/owner/add'
    | '/owner/bookings'
    | '/farmer/'
    | '/owner/'
    | '/farmer/storage/$id'
    | '/farmer/storage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/help'
    | '/login'
    | '/market'
    | '/orders'
    | '/settings'
    | '/farmer/active'
    | '/farmer/contract'
    | '/farmer/payment'
    | '/owner/add'
    | '/owner/bookings'
    | '/farmer'
    | '/owner'
    | '/farmer/storage/$id'
    | '/farmer/storage'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/help'
    | '/login'
    | '/market'
    | '/orders'
    | '/settings'
    | '/farmer/active'
    | '/farmer/contract'
    | '/farmer/payment'
    | '/owner/add'
    | '/owner/bookings'
    | '/farmer/'
    | '/owner/'
    | '/farmer/storage/$id'
    | '/farmer/storage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  MarketRoute: typeof MarketRoute
  OrdersRoute: typeof OrdersRoute
  SettingsRoute: typeof SettingsRoute
  FarmerActiveRoute: typeof FarmerActiveRoute
  FarmerContractRoute: typeof FarmerContractRoute
  FarmerPaymentRoute: typeof FarmerPaymentRoute
  OwnerAddRoute: typeof OwnerAddRoute
  OwnerBookingsRoute: typeof OwnerBookingsRoute
  FarmerIndexRoute: typeof FarmerIndexRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  FarmerStorageIdRoute: typeof FarmerStorageIdRoute
  FarmerStorageIndexRoute: typeof FarmerStorageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/': {
      id: '/farmer/'
      path: '/farmer'
      fullPath: '/farmer/'
      preLoaderRoute: typeof FarmerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/bookings': {
      id: '/owner/bookings'
      path: '/owner/bookings'
      fullPath: '/owner/bookings'
      preLoaderRoute: typeof OwnerBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/add': {
      id: '/owner/add'
      path: '/owner/add'
      fullPath: '/owner/add'
      preLoaderRoute: typeof OwnerAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/payment': {
      id: '/farmer/payment'
      path: '/farmer/payment'
      fullPath: '/farmer/payment'
      preLoaderRoute: typeof FarmerPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/contract': {
      id: '/farmer/contract'
      path: '/farmer/contract'
      fullPath: '/farmer/contract'
      preLoaderRoute: typeof FarmerContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/active': {
      id: '/farmer/active'
      path: '/farmer/active'
      fullPath: '/farmer/active'
      preLoaderRoute: typeof FarmerActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/storage/': {
      id: '/farmer/storage/'
      path: '/farmer/storage'
      fullPath: '/farmer/storage/'
      preLoaderRoute: typeof FarmerStorageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/storage/$id': {
      id: '/farmer/storage/$id'
      path: '/farmer/storage/$id'
      fullPath: '/farmer/storage/$id'
      preLoaderRoute: typeof FarmerStorageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  MarketRoute: MarketRoute,
  OrdersRoute: OrdersRoute,
  SettingsRoute: SettingsRoute,
  FarmerActiveRoute: FarmerActiveRoute,
  FarmerContractRoute: FarmerContractRoute,
  FarmerPaymentRoute: FarmerPaymentRoute,
  OwnerAddRoute: OwnerAddRoute,
  OwnerBookingsRoute: OwnerBookingsRoute,
  FarmerIndexRoute: FarmerIndexRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  FarmerStorageIdRoute: FarmerStorageIdRoute,
  FarmerStorageIndexRoute: FarmerStorageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
